### PR TITLE
Fix Fallback Message (CU-mgz8vq)

### PR DESCRIPTION
**Pull request by risatronic**
- Change `location_human` to `display_name` to match db and fix display issue

### CODE REVIEW

**Comment by trisapeace** [comment]
Task linked: [CU-mgz8vq Fix bug - Fallback message doesn't use human readable location](https://app.clickup.com/t/mgz8vq)

**Review by trisapeace — APPROVED** [review]
This looks right to me. 

Have you checked that it works on the dev server?

**Comment by risatronic** [comment]
It does indeed work :)

**Review by mariocimet — APPROVED** [review]

**Comment by mariocimet** [comment]
thanks Marisa!

**Pull request merged**
