### PR TITLE
Remove commas/clean-up (CU-k725tk)

### PR DESCRIPTION
**Pull request by risatronic**
- Remove commas from `Location.js` and `Session.js`
- Update some references to ODetect to reflect name change to Brave Sensor

### CODE REVIEW

**Comment by risatronic** [comment]
Please ignore the massive history of renaming/closing/etc, it doesn't seem to be working to link to clickup. @trisapeace do you happen to know why that might be the case?

**Comment by trisapeace** [comment]
Maybe because of the name change on the repo. I'll check in ClickUp.

**Comment by trisapeace** [comment]
Yup, I had to make a change in ClickUp. Hopefully it'll work now.

**Review by trisapeace — APPROVED** [review]

**Comment by risatronic** [comment]
> Yup, I had to make a change in ClickUp. Hopefully it'll work now.

Doesn't seem to be working :(

**Comment by risatronic** [comment]
Not the end of the world if it doesn't I suppose haha

**Comment by trisapeace** [comment]
You're right. I still didn't have the config right. Can you please try again now?

**Comment by trisapeace** [comment]
Task linked: [CU-k725tk Remove Commas/Clean-up](https://app.clickup.com/t/k725tk)

**Comment by trisapeace** [comment]
Ah! There it is. Sorry about the confusion. I'm glad you noticed it before we went too long without that linking working.

**Comment by risatronic** [comment]
> Ah! There it is. Sorry about the confusion. I'm glad you noticed it before we went too long without that linking working.

All good, thank you for sorting it out! 😊

**Review by sampathsatti — APPROVED** [review]
LGTM!

**Pull request merged**
